"""
Build the public data file (institutions.js) for the Posterior Fossa Society membership map.

Run:  python build_membership_map.py /path/to/Membership_List.xlsx

Inputs (both stay private and are blocked by .gitignore):
  - the membership spreadsheet (Membership tab: Email and Country columns are read)
  - institution_lookup.csv: one row per email domain -> institution, city, country, lat, lon, status

Output (safe to publish): institutions.js, listing cities, the institutions in each city, and
the countries where members work. No names, emails, or member counts are written.

What it does, in plain terms:
  1. Reads each member's email domain and country.
  2. Looks the domain up in institution_lookup.csv. Rows marked "include" become map pins;
     rows marked "exclude" (personal email, private practice, NHS-wide addresses) do not.
  3. Groups institutions by city, so each pin lists the institutions in that city.
  4. Lists every country with at least one member, whether or not the member has a pin.
"""
import csv, json, sys, datetime
from collections import defaultdict
from openpyxl import load_workbook

PERSONAL = {"gmail.com", "yahoo.com", "hotmail.com", "outlook.com", "icloud.com", "aol.com", "live.com",
            "me.com", "msn.com", "hotmail.co.uk", "yahoo.co.uk", "googlemail.com", "protonmail.com"}
# Tidy the free-text Country column so each country appears once.
COUNTRY_FIX = {"UK": "United Kingdom", "USA": "United States", "US": "United States", "Irelane": "Ireland", "Dublin": "Ireland"}


def main(xlsx, lookup_path="institution_lookup.csv", out="institutions.js"):
    lookup = {r["domain"]: r for r in csv.DictReader(open(lookup_path, encoding="utf-8"))}
    ws = load_workbook(xlsx, read_only=True)["Membership"]
    rows = list(ws.iter_rows(values_only=True))
    hdr_i = next(i for i, r in enumerate(rows) if r and "Email" in [str(v).strip() if v else "" for v in r])
    hdr = [str(v).strip() if v else "" for v in rows[hdr_i]]
    ei, ci = hdr.index("Email"), hdr.index("Country")

    cities = {}                      # (city, country) -> {lat, lon, institutions}
    countries, unknown = set(), set()
    for r in rows[hdr_i + 1:]:
        if not r or len(r) <= max(ei, ci):
            continue
        email = str(r[ei] or "").strip().lower()
        domain = email.split("@")[-1] if "@" in email else ""
        row = lookup.get(domain)
        country = COUNTRY_FIX.get(str(r[ci] or "").strip(), str(r[ci] or "").strip())
        if row and row["country"]:
            country = row["country"]            # the institution's country wins over free text
        if country and len(country) < 40 and "," not in country:
            countries.add(country)
        if not domain or domain in PERSONAL:
            continue
        if not row:
            unknown.add(domain)
            continue
        if row["status"] != "include":
            continue
        key = (row["city"], row["country"])
        c = cities.setdefault(key, {"city": row["city"], "country": row["country"],
                                    "lat": float(row["lat"]), "lon": float(row["lon"]), "institutions": set()})
        c["institutions"].add(row["institution"])

    pins = sorted(({**c, "institutions": sorted(c["institutions"])} for c in cities.values()),
                  key=lambda c: (c["country"], c["city"]))
    data = {"updated": datetime.date.today().isoformat(), "countries": sorted(countries), "cities": pins}
    with open(out, "w", encoding="utf-8") as f:
        f.write("// Generated by build_membership_map.py. Do not edit by hand.\n")
        f.write("window.PFS_MEMBERSHIP = " + json.dumps(data, ensure_ascii=False, indent=1) + ";\n")
    n_inst = sum(len(c["institutions"]) for c in pins)
    print(f"Wrote {len(pins)} city pins, {n_inst} institutions, {len(countries)} countries to {out}")
    if unknown:
        print("Domains not in institution_lookup.csv (add a row for each, then rerun):", ", ".join(sorted(unknown)))


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit("Usage: python build_membership_map.py /path/to/Membership_List.xlsx")
    main(sys.argv[1])
