// Generated by build_membership_map.py. Do not edit by hand.
window.PFS_MEMBERSHIP = {
 "updated": "2026-09-25",
 "countries": [
  "Australia",
  "Austria",
  "Belgium",
  "Canada",
  "Costa Rica",
  "Denmark",
  "France",
  "Germany",
  "Iceland",
  "India",
  "Ireland",
  "Italy",
  "Netherlands",
  "Norway",
  "Pakistan",
  "Russia",
  "Singapore",
  "Slovenia",
  "Spain",
  "Sweden",
  "United Kingdom",
  "United States"
 ],
 "cities": [
  {
   "city": "Brisbane",
   "country": "Australia",
   "lat": -27.4975,
   "lon": 153.0137,
   "institutions": [
    "Queensland University of Technology",
    "University of Queensland"
   ]
  },
  {
   "city": "Melbourne",
   "country": "Australia",
   "lat": -37.7937,
   "lon": 144.9493,
   "institutions": [
    "Murdoch Children's Research Institute",
    "Royal Children's Hospital Melbourne"
   ]
  },
  {
   "city": "Perth",
   "country": "Australia",
   "lat": -31.9505,
   "lon": 115.8605,
   "institutions": [
    "WA Health"
   ]
  },
  {
   "city": "Sydney",
   "country": "Australia",
   "lat": -33.8886,
   "lon": 151.1873,
   "institutions": [
    "NSW Health",
    "University of Sydney"
   ]
  },
  {
   "city": "Vienna",
   "country": "Austria",
   "lat": 48.2205,
   "lon": 16.347,
   "institutions": [
    "Medical University of Vienna"
   ]
  },
  {
   "city": "Brussels",
   "country": "Belgium",
   "lat": 50.8126,
   "lon": 4.3817,
   "institutions": [
    "UCLouvain",
    "Université libre de Bruxelles"
   ]
  },
  {
   "city": "Leuven",
   "country": "Belgium",
   "lat": 50.8804,
   "lon": 4.6716,
   "institutions": [
    "University Hospitals Leuven"
   ]
  },
  {
   "city": "Toronto",
   "country": "Canada",
   "lat": 43.6572,
   "lon": -79.3882,
   "institutions": [
    "The Hospital for Sick Children (SickKids)"
   ]
  },
  {
   "city": "Copenhagen",
   "country": "Denmark",
   "lat": 55.659,
   "lon": 12.589,
   "institutions": [
    "Capital Region of Denmark hospitals",
    "University of Copenhagen"
   ]
  },
  {
   "city": "Angers",
   "country": "France",
   "lat": 47.4816,
   "lon": -0.5539,
   "institutions": [
    "Angers University Hospital"
   ]
  },
  {
   "city": "Villejuif",
   "country": "France",
   "lat": 48.7946,
   "lon": 2.3522,
   "institutions": [
    "Gustave Roussy"
   ]
  },
  {
   "city": "Berlin",
   "country": "Germany",
   "lat": 52.526,
   "lon": 13.3777,
   "institutions": [
    "Charité – Universitätsmedizin Berlin"
   ]
  },
  {
   "city": "Hamburg",
   "country": "Germany",
   "lat": 53.5895,
   "lon": 9.976,
   "institutions": [
    "University Medical Center Hamburg-Eppendorf"
   ]
  },
  {
   "city": "Hannover",
   "country": "Germany",
   "lat": 52.384,
   "lon": 9.805,
   "institutions": [
    "Hannover Medical School"
   ]
  },
  {
   "city": "Würzburg",
   "country": "Germany",
   "lat": 49.8014,
   "lon": 9.957,
   "institutions": [
    "University Hospital Würzburg"
   ]
  },
  {
   "city": "Kolkata",
   "country": "India",
   "lat": 22.5797,
   "lon": 88.48,
   "institutions": [
    "Tata Medical Center"
   ]
  },
  {
   "city": "Cork",
   "country": "Ireland",
   "lat": 51.8818,
   "lon": -8.5022,
   "institutions": [
    "Cork University Hospital"
   ]
  },
  {
   "city": "Dublin",
   "country": "Ireland",
   "lat": 53.326,
   "lon": -6.315,
   "institutions": [
    "Children's Health Ireland"
   ]
  },
  {
   "city": "Bosisio Parini",
   "country": "Italy",
   "lat": 45.801,
   "lon": 9.288,
   "institutions": [
    "Scientific Institute IRCCS Eugenio Medea"
   ]
  },
  {
   "city": "Rome",
   "country": "Italy",
   "lat": 41.8984,
   "lon": 12.4595,
   "institutions": [
    "Bambino Gesù Children's Hospital"
   ]
  },
  {
   "city": "Turin",
   "country": "Italy",
   "lat": 45.069,
   "lon": 7.689,
   "institutions": [
    "University of Turin"
   ]
  },
  {
   "city": "Groningen",
   "country": "Netherlands",
   "lat": 53.2215,
   "lon": 6.576,
   "institutions": [
    "University Medical Center Groningen",
    "University of Groningen"
   ]
  },
  {
   "city": "Rotterdam",
   "country": "Netherlands",
   "lat": 51.9107,
   "lon": 4.469,
   "institutions": [
    "Erasmus MC"
   ]
  },
  {
   "city": "Utrecht",
   "country": "Netherlands",
   "lat": 52.0867,
   "lon": 5.1785,
   "institutions": [
    "Princess Máxima Center for Pediatric Oncology",
    "University Medical Center Utrecht"
   ]
  },
  {
   "city": "Karachi",
   "country": "Pakistan",
   "lat": 24.892,
   "lon": 67.075,
   "institutions": [
    "Aga Khan University"
   ]
  },
  {
   "city": "Singapore",
   "country": "Singapore",
   "lat": 1.2966,
   "lon": 103.7764,
   "institutions": [
    "National University of Singapore"
   ]
  },
  {
   "city": "Ljubljana",
   "country": "Slovenia",
   "lat": 46.0569,
   "lon": 14.523,
   "institutions": [
    "University Medical Centre Ljubljana"
   ]
  },
  {
   "city": "Madrid",
   "country": "Spain",
   "lat": 40.4168,
   "lon": -3.7038,
   "institutions": [
    "Madrid regional health service"
   ]
  },
  {
   "city": "Lund",
   "country": "Sweden",
   "lat": 55.711,
   "lon": 13.199,
   "institutions": [
    "Lund University"
   ]
  },
  {
   "city": "Uppsala",
   "country": "Sweden",
   "lat": 59.8586,
   "lon": 17.6389,
   "institutions": [
    "Uppsala University"
   ]
  },
  {
   "city": "Bristol",
   "country": "United Kingdom",
   "lat": 51.4585,
   "lon": -2.603,
   "institutions": [
    "University Hospitals Bristol and Weston",
    "University of Bristol"
   ]
  },
  {
   "city": "Glasgow",
   "country": "United Kingdom",
   "lat": 55.862,
   "lon": -4.34,
   "institutions": [
    "NHS Greater Glasgow and Clyde"
   ]
  },
  {
   "city": "Liverpool",
   "country": "United Kingdom",
   "lat": 53.4196,
   "lon": -2.897,
   "institutions": [
    "Alder Hey Children's Hospital"
   ]
  },
  {
   "city": "London",
   "country": "United Kingdom",
   "lat": 51.5224,
   "lon": -0.1204,
   "institutions": [
    "Great Ormond Street Hospital",
    "University College London"
   ]
  },
  {
   "city": "Nottingham",
   "country": "United Kingdom",
   "lat": 52.938,
   "lon": -1.196,
   "institutions": [
    "University of Nottingham"
   ]
  },
  {
   "city": "Ann Arbor",
   "country": "United States",
   "lat": 42.283,
   "lon": -83.728,
   "institutions": [
    "Michigan Medicine"
   ]
  },
  {
   "city": "Baltimore",
   "country": "United States",
   "lat": 39.2982,
   "lon": -76.593,
   "institutions": [
    "Kennedy Krieger Institute"
   ]
  },
  {
   "city": "Boston",
   "country": "United States",
   "lat": 42.3374,
   "lon": -71.1053,
   "institutions": [
    "Boston Children's Hospital",
    "Massachusetts General Hospital"
   ]
  },
  {
   "city": "Chicago",
   "country": "United States",
   "lat": 41.8961,
   "lon": -87.6219,
   "institutions": [
    "Ann & Robert H. Lurie Children's Hospital of Chicago"
   ]
  },
  {
   "city": "Columbus",
   "country": "United States",
   "lat": 39.953,
   "lon": -82.979,
   "institutions": [
    "Nationwide Children's Hospital"
   ]
  },
  {
   "city": "Duluth",
   "country": "United States",
   "lat": 46.8189,
   "lon": -92.084,
   "institutions": [
    "University of Minnesota Duluth"
   ]
  },
  {
   "city": "Houston",
   "country": "United States",
   "lat": 29.708,
   "lon": -95.402,
   "institutions": [
    "Baylor College of Medicine",
    "MD Anderson Cancer Center",
    "Texas Children's Hospital"
   ]
  },
  {
   "city": "Los Angeles",
   "country": "United States",
   "lat": 34.0975,
   "lon": -118.2908,
   "institutions": [
    "Children's Hospital Los Angeles"
   ]
  },
  {
   "city": "Memphis",
   "country": "United States",
   "lat": 35.1531,
   "lon": -90.0442,
   "institutions": [
    "Semmes Murphey Clinic",
    "St. Jude Children's Research Hospital"
   ]
  },
  {
   "city": "Miami",
   "country": "United States",
   "lat": 25.742,
   "lon": -80.294,
   "institutions": [
    "Nicklaus Children's Hospital"
   ]
  },
  {
   "city": "New York",
   "country": "United States",
   "lat": 40.742,
   "lon": -73.974,
   "institutions": [
    "NYU Langone Health"
   ]
  },
  {
   "city": "Philadelphia",
   "country": "United States",
   "lat": 39.9483,
   "lon": -75.194,
   "institutions": [
    "Children's Hospital of Philadelphia"
   ]
  },
  {
   "city": "Washington, DC",
   "country": "United States",
   "lat": 38.927,
   "lon": -77.014,
   "institutions": [
    "Children's National Hospital"
   ]
  }
 ]
};
